//Post action
const ALL_ARTICLES = "TOUS LES ARTICLES";
const ALL_AGENDA = "TOUS LES AGENDAS";
const ALL_IMAGE_DESCRIPT = "TOUTES LES IMAGES";
const ALL_FORMATION = "TOUTES LES FORMATIONS";
const ALL_ORGANIGRAMME = "TOUS LES ORGANIGRAMMES";
const ONE_ARTICLE = "UN SEUL ARTICLE";

//User action
const CONNEXION = "CONNEXION";

export {
  ALL_ARTICLES,
  ALL_AGENDA,
  ALL_IMAGE_DESCRIPT,
  ALL_FORMATION,
  ALL_ORGANIGRAMME,
  ONE_ARTICLE,
  CONNEXION
};
